# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CancelRegistrationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CancelRegistrationDialog(object):
    def setupUi(self, CancelRegistrationDialog):
        CancelRegistrationDialog.setObjectName("CancelRegistrationDialog")
        CancelRegistrationDialog.resize(238, 192)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        CancelRegistrationDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/cancelRegistration.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CancelRegistrationDialog.setWindowIcon(icon)
        CancelRegistrationDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        CancelRegistrationDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.verticalLayout = QtWidgets.QVBoxLayout(CancelRegistrationDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.FLayoutFields = QtWidgets.QFormLayout()
        self.FLayoutFields.setObjectName("FLayoutFields")
        self.lblPassengerId = QtWidgets.QLabel(CancelRegistrationDialog)
        self.lblPassengerId.setObjectName("lblPassengerId")
        self.FLayoutFields.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblPassengerId)
        self.HLayoutTourId = QtWidgets.QHBoxLayout()
        self.HLayoutTourId.setObjectName("HLayoutTourId")
        self.btnSearchPassengerId = QtWidgets.QPushButton(CancelRegistrationDialog)
        self.btnSearchPassengerId.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/icons/searchTour.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSearchPassengerId.setIcon(icon1)
        self.btnSearchPassengerId.setIconSize(QtCore.QSize(25, 25))
        self.btnSearchPassengerId.setObjectName("btnSearchPassengerId")
        self.HLayoutTourId.addWidget(self.btnSearchPassengerId)
        self.txtPassengerId = QtWidgets.QLineEdit(CancelRegistrationDialog)
        self.txtPassengerId.setObjectName("txtPassengerId")
        self.HLayoutTourId.addWidget(self.txtPassengerId)
        self.FLayoutFields.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.HLayoutTourId)
        self.lblTourId = QtWidgets.QLabel(CancelRegistrationDialog)
        self.lblTourId.setObjectName("lblTourId")
        self.FLayoutFields.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblTourId)
        self.txtTourId = QtWidgets.QLineEdit(CancelRegistrationDialog)
        self.txtTourId.setEnabled(False)
        self.txtTourId.setObjectName("txtTourId")
        self.FLayoutFields.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtTourId)
        self.verticalLayout.addLayout(self.FLayoutFields)
        self.lblError = QtWidgets.QLabel(CancelRegistrationDialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblError.setPalette(palette)
        self.lblError.setObjectName("lblError")
        self.verticalLayout.addWidget(self.lblError)
        self.HLayoutButtons = QtWidgets.QHBoxLayout()
        self.HLayoutButtons.setObjectName("HLayoutButtons")
        self.btnDelete = QtWidgets.QPushButton(CancelRegistrationDialog)
        self.btnDelete.setIcon(icon)
        self.btnDelete.setIconSize(QtCore.QSize(40, 40))
        self.btnDelete.setObjectName("btnDelete")
        self.HLayoutButtons.addWidget(self.btnDelete)
        self.btnReturn = QtWidgets.QPushButton(CancelRegistrationDialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/icons/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReturn.setIcon(icon2)
        self.btnReturn.setIconSize(QtCore.QSize(40, 40))
        self.btnReturn.setObjectName("btnReturn")
        self.HLayoutButtons.addWidget(self.btnReturn)
        self.verticalLayout.addLayout(self.HLayoutButtons)

        self.retranslateUi(CancelRegistrationDialog)
        QtCore.QMetaObject.connectSlotsByName(CancelRegistrationDialog)

    def retranslateUi(self, CancelRegistrationDialog):
        _translate = QtCore.QCoreApplication.translate
        CancelRegistrationDialog.setWindowTitle(_translate("CancelRegistrationDialog", "انصراف از اردو"))
        self.lblPassengerId.setText(_translate("CancelRegistrationDialog", "کد ملی مسافر"))
        self.lblTourId.setText(_translate("CancelRegistrationDialog", "کد اردو"))
        self.lblError.setText(_translate("CancelRegistrationDialog", "خطا"))
        self.btnDelete.setText(_translate("CancelRegistrationDialog", "انصراف از اردو"))
        self.btnReturn.setText(_translate("CancelRegistrationDialog", "بازگشت"))
        self.btnReturn.setShortcut(_translate("CancelRegistrationDialog", "Ctrl+S"))
import UI.resource_rc
