# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteTourDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteTourDialog(object):
    def setupUi(self, DeleteTourDialog):
        DeleteTourDialog.setObjectName("DeleteTourDialog")
        DeleteTourDialog.resize(289, 151)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        DeleteTourDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/deleteTour.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DeleteTourDialog.setWindowIcon(icon)
        DeleteTourDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        DeleteTourDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.verticalLayout = QtWidgets.QVBoxLayout(DeleteTourDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.FLayoutFields = QtWidgets.QFormLayout()
        self.FLayoutFields.setObjectName("FLayoutFields")
        self.label = QtWidgets.QLabel(DeleteTourDialog)
        self.label.setObjectName("label")
        self.FLayoutFields.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.HLayoutTourId = QtWidgets.QHBoxLayout()
        self.HLayoutTourId.setObjectName("HLayoutTourId")
        self.btnSearchId = QtWidgets.QPushButton(DeleteTourDialog)
        self.btnSearchId.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/icons/searchTour.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSearchId.setIcon(icon1)
        self.btnSearchId.setIconSize(QtCore.QSize(25, 25))
        self.btnSearchId.setObjectName("btnSearchId")
        self.HLayoutTourId.addWidget(self.btnSearchId)
        self.txtTourId = QtWidgets.QLineEdit(DeleteTourDialog)
        self.txtTourId.setObjectName("txtTourId")
        self.HLayoutTourId.addWidget(self.txtTourId)
        self.FLayoutFields.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.HLayoutTourId)
        self.verticalLayout.addLayout(self.FLayoutFields)
        self.lblError = QtWidgets.QLabel(DeleteTourDialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblError.setPalette(palette)
        self.lblError.setObjectName("lblError")
        self.verticalLayout.addWidget(self.lblError)
        self.HLayoutButtons = QtWidgets.QHBoxLayout()
        self.HLayoutButtons.setObjectName("HLayoutButtons")
        self.btnDelete = QtWidgets.QPushButton(DeleteTourDialog)
        self.btnDelete.setIcon(icon)
        self.btnDelete.setIconSize(QtCore.QSize(40, 40))
        self.btnDelete.setObjectName("btnDelete")
        self.HLayoutButtons.addWidget(self.btnDelete)
        self.btnReturn = QtWidgets.QPushButton(DeleteTourDialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/icons/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReturn.setIcon(icon2)
        self.btnReturn.setIconSize(QtCore.QSize(40, 40))
        self.btnReturn.setObjectName("btnReturn")
        self.HLayoutButtons.addWidget(self.btnReturn)
        self.verticalLayout.addLayout(self.HLayoutButtons)

        self.retranslateUi(DeleteTourDialog)
        QtCore.QMetaObject.connectSlotsByName(DeleteTourDialog)

    def retranslateUi(self, DeleteTourDialog):
        _translate = QtCore.QCoreApplication.translate
        DeleteTourDialog.setWindowTitle(_translate("DeleteTourDialog", "حذف اردو"))
        self.label.setText(_translate("DeleteTourDialog", "کد اردو"))
        self.txtTourId.setPlaceholderText(_translate("DeleteTourDialog", "کد اردوها را با - از هم جدا کنید"))
        self.lblError.setText(_translate("DeleteTourDialog", "خطا"))
        self.btnDelete.setText(_translate("DeleteTourDialog", "حذف اردوها"))
        self.btnReturn.setText(_translate("DeleteTourDialog", "بازگشت"))
        self.btnReturn.setShortcut(_translate("DeleteTourDialog", "Ctrl+S"))
import UI.resource_rc
