# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MessageDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MessageDialog(object):
    def setupUi(self, MessageDialog):
        MessageDialog.setObjectName("MessageDialog")
        MessageDialog.resize(330, 120)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MessageDialog.setWindowIcon(icon)
        MessageDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        MessageDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        MessageDialog.setModal(False)
        self.lblMessage = QtWidgets.QLabel(MessageDialog)
        self.lblMessage.setGeometry(QtCore.QRect(50, 20, 181, 30))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.lblMessage.setFont(font)
        self.lblMessage.setObjectName("lblMessage")
        self.lblIcon = QtWidgets.QLabel(MessageDialog)
        self.lblIcon.setGeometry(QtCore.QRect(260, 10, 60, 60))
        self.lblIcon.setMinimumSize(QtCore.QSize(60, 60))
        self.lblIcon.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.lblIcon.setFont(font)
        self.lblIcon.setText("")
        self.lblIcon.setPixmap(QtGui.QPixmap(":/icons/resources/icons/info.png"))
        self.lblIcon.setScaledContents(True)
        self.lblIcon.setObjectName("lblIcon")
        self.btnClose = QtWidgets.QPushButton(MessageDialog)
        self.btnClose.setGeometry(QtCore.QRect(110, 80, 100, 30))
        self.btnClose.setMinimumSize(QtCore.QSize(100, 30))
        self.btnClose.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.btnClose.setFont(font)
        self.btnClose.setAutoDefault(False)
        self.btnClose.setDefault(True)
        self.btnClose.setObjectName("btnClose")

        self.retranslateUi(MessageDialog)
        QtCore.QMetaObject.connectSlotsByName(MessageDialog)

    def retranslateUi(self, MessageDialog):
        _translate = QtCore.QCoreApplication.translate
        MessageDialog.setWindowTitle(_translate("MessageDialog", "پیام"))
        self.lblMessage.setText(_translate("MessageDialog", "عملیات با موفقیت انجام شد."))
        self.btnClose.setText(_translate("MessageDialog", "بستن"))
import UI.resource_rc
