# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MessageDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MessageDialog(object):
    def setupUi(self, MessageDialog):
        MessageDialog.setObjectName("MessageDialog")
        MessageDialog.resize(269, 136)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MessageDialog.sizePolicy().hasHeightForWidth())
        MessageDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MessageDialog.setWindowIcon(icon)
        MessageDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        MessageDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        MessageDialog.setModal(False)
        self.VLayoutMain = QtWidgets.QVBoxLayout(MessageDialog)
        self.VLayoutMain.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.VLayoutMain.setContentsMargins(10, 10, 10, 10)
        self.VLayoutMain.setSpacing(10)
        self.VLayoutMain.setObjectName("VLayoutMain")
        self.HLayoutMessage = QtWidgets.QHBoxLayout()
        self.HLayoutMessage.setSpacing(10)
        self.HLayoutMessage.setObjectName("HLayoutMessage")
        self.lblIcon = QtWidgets.QLabel(MessageDialog)
        self.lblIcon.setMinimumSize(QtCore.QSize(64, 64))
        self.lblIcon.setMaximumSize(QtCore.QSize(64, 64))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.lblIcon.setFont(font)
        self.lblIcon.setText("")
        self.lblIcon.setPixmap(QtGui.QPixmap(":/icons/resources/icons/info.png"))
        self.lblIcon.setScaledContents(True)
        self.lblIcon.setObjectName("lblIcon")
        self.HLayoutMessage.addWidget(self.lblIcon)
        self.lblMessage = QtWidgets.QLabel(MessageDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMessage.sizePolicy().hasHeightForWidth())
        self.lblMessage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.lblMessage.setFont(font)
        self.lblMessage.setTextFormat(QtCore.Qt.AutoText)
        self.lblMessage.setObjectName("lblMessage")
        self.HLayoutMessage.addWidget(self.lblMessage)
        self.VLayoutMain.addLayout(self.HLayoutMessage)
        self.HLayoutButton = QtWidgets.QHBoxLayout()
        self.HLayoutButton.setSpacing(10)
        self.HLayoutButton.setObjectName("HLayoutButton")
        self.btnClose = QtWidgets.QPushButton(MessageDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClose.sizePolicy().hasHeightForWidth())
        self.btnClose.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.btnClose.setFont(font)
        self.btnClose.setAutoDefault(False)
        self.btnClose.setDefault(True)
        self.btnClose.setObjectName("btnClose")
        self.HLayoutButton.addWidget(self.btnClose, 0, QtCore.Qt.AlignVCenter)
        self.VLayoutMain.addLayout(self.HLayoutButton)

        self.retranslateUi(MessageDialog)
        QtCore.QMetaObject.connectSlotsByName(MessageDialog)

    def retranslateUi(self, MessageDialog):
        _translate = QtCore.QCoreApplication.translate
        MessageDialog.setWindowTitle(_translate("MessageDialog", "پیام"))
        self.lblMessage.setText(_translate("MessageDialog", "عملیات با موفقیت انجام شد."))
        self.btnClose.setText(_translate("MessageDialog", "بستن"))
import UI.resource_rc
