# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectRoleDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectRoleDialog(object):
    def setupUi(self, SelectRoleDialog):
        SelectRoleDialog.setObjectName("SelectRoleDialog")
        SelectRoleDialog.resize(300, 160)
        SelectRoleDialog.setMinimumSize(QtCore.QSize(300, 160))
        SelectRoleDialog.setMaximumSize(QtCore.QSize(300, 160))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SelectRoleDialog.setWindowIcon(icon)
        SelectRoleDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        SelectRoleDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.lblInfo = QtWidgets.QLabel(SelectRoleDialog)
        self.lblInfo.setGeometry(QtCore.QRect(75, 20, 150, 30))
        self.lblInfo.setMinimumSize(QtCore.QSize(150, 30))
        self.lblInfo.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.lblInfo.setFont(font)
        self.lblInfo.setObjectName("lblInfo")
        self.btnManager = QtWidgets.QPushButton(SelectRoleDialog)
        self.btnManager.setGeometry(QtCore.QRect(160, 70, 120, 70))
        self.btnManager.setMinimumSize(QtCore.QSize(120, 70))
        self.btnManager.setMaximumSize(QtCore.QSize(120, 70))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.btnManager.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/icons/manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnManager.setIcon(icon1)
        self.btnManager.setIconSize(QtCore.QSize(60, 60))
        self.btnManager.setAutoDefault(False)
        self.btnManager.setObjectName("btnManager")
        self.btnUser = QtWidgets.QPushButton(SelectRoleDialog)
        self.btnUser.setGeometry(QtCore.QRect(20, 70, 120, 70))
        self.btnUser.setMinimumSize(QtCore.QSize(120, 70))
        self.btnUser.setMaximumSize(QtCore.QSize(120, 70))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.btnUser.setFont(font)
        self.btnUser.setIcon(icon)
        self.btnUser.setIconSize(QtCore.QSize(60, 60))
        self.btnUser.setAutoDefault(False)
        self.btnUser.setDefault(True)
        self.btnUser.setObjectName("btnUser")

        self.retranslateUi(SelectRoleDialog)
        QtCore.QMetaObject.connectSlotsByName(SelectRoleDialog)

    def retranslateUi(self, SelectRoleDialog):
        _translate = QtCore.QCoreApplication.translate
        SelectRoleDialog.setWindowTitle(_translate("SelectRoleDialog", "انتخاب نقش"))
        self.lblInfo.setText(_translate("SelectRoleDialog", "لطفا نقش خود را انتخاب کنید"))
        self.btnManager.setText(_translate("SelectRoleDialog", "مدیر فنی"))
        self.btnUser.setText(_translate("SelectRoleDialog", "کارشناس"))
import UI.resource_rc
