# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectRoleDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectRoleDialog(object):
    def setupUi(self, SelectRoleDialog):
        SelectRoleDialog.setObjectName("SelectRoleDialog")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SelectRoleDialog.setWindowIcon(icon)
        SelectRoleDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        SelectRoleDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        SelectRoleDialog.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectRoleDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblInfo = QtWidgets.QLabel(SelectRoleDialog)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.lblInfo.setFont(font)
        self.lblInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblInfo.setObjectName("lblInfo")
        self.verticalLayout.addWidget(self.lblInfo)
        self.HLayoutButtons = QtWidgets.QHBoxLayout()
        self.HLayoutButtons.setSpacing(10)
        self.HLayoutButtons.setObjectName("HLayoutButtons")
        self.btnManager = QtWidgets.QPushButton(SelectRoleDialog)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.btnManager.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/icons/manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnManager.setIcon(icon1)
        self.btnManager.setIconSize(QtCore.QSize(60, 60))
        self.btnManager.setAutoDefault(False)
        self.btnManager.setObjectName("btnManager")
        self.HLayoutButtons.addWidget(self.btnManager)
        self.btnUser = QtWidgets.QPushButton(SelectRoleDialog)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.btnUser.setFont(font)
        self.btnUser.setIcon(icon)
        self.btnUser.setIconSize(QtCore.QSize(60, 60))
        self.btnUser.setAutoDefault(False)
        self.btnUser.setDefault(True)
        self.btnUser.setObjectName("btnUser")
        self.HLayoutButtons.addWidget(self.btnUser)
        self.verticalLayout.addLayout(self.HLayoutButtons)

        self.retranslateUi(SelectRoleDialog)
        QtCore.QMetaObject.connectSlotsByName(SelectRoleDialog)

    def retranslateUi(self, SelectRoleDialog):
        _translate = QtCore.QCoreApplication.translate
        SelectRoleDialog.setWindowTitle(_translate("SelectRoleDialog", "انتخاب نقش"))
        self.lblInfo.setText(_translate("SelectRoleDialog", "لطفا نقش خود را انتخاب کنید"))
        self.btnManager.setText(_translate("SelectRoleDialog", "مدیر فنی"))
        self.btnUser.setText(_translate("SelectRoleDialog", "کارشناس"))
import UI.resource_rc
