# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YesNoDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YesNoDialog(object):
    def setupUi(self, YesNoDialog):
        YesNoDialog.setObjectName("YesNoDialog")
        YesNoDialog.resize(330, 120)
        YesNoDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        YesNoDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        YesNoDialog.setModal(False)
        self.lblMessage = QtWidgets.QLabel(YesNoDialog)
        self.lblMessage.setGeometry(QtCore.QRect(50, 20, 181, 30))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.lblMessage.setFont(font)
        self.lblMessage.setObjectName("lblMessage")
        self.lblIcon = QtWidgets.QLabel(YesNoDialog)
        self.lblIcon.setGeometry(QtCore.QRect(260, 10, 60, 60))
        self.lblIcon.setMinimumSize(QtCore.QSize(60, 60))
        self.lblIcon.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.lblIcon.setFont(font)
        self.lblIcon.setText("")
        self.lblIcon.setPixmap(QtGui.QPixmap(":/icons/resources/icons/question.png"))
        self.lblIcon.setScaledContents(True)
        self.lblIcon.setObjectName("lblIcon")
        self.btnYes = QtWidgets.QPushButton(YesNoDialog)
        self.btnYes.setGeometry(QtCore.QRect(180, 80, 100, 30))
        self.btnYes.setMinimumSize(QtCore.QSize(100, 30))
        self.btnYes.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.btnYes.setFont(font)
        self.btnYes.setAutoDefault(False)
        self.btnYes.setDefault(True)
        self.btnYes.setObjectName("btnYes")
        self.btnNo = QtWidgets.QPushButton(YesNoDialog)
        self.btnNo.setGeometry(QtCore.QRect(50, 80, 100, 30))
        self.btnNo.setMinimumSize(QtCore.QSize(100, 30))
        self.btnNo.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.btnNo.setFont(font)
        self.btnNo.setAutoDefault(False)
        self.btnNo.setObjectName("btnNo")

        self.retranslateUi(YesNoDialog)
        QtCore.QMetaObject.connectSlotsByName(YesNoDialog)

    def retranslateUi(self, YesNoDialog):
        _translate = QtCore.QCoreApplication.translate
        YesNoDialog.setWindowTitle(_translate("YesNoDialog", "خروج"))
        self.lblMessage.setText(_translate("YesNoDialog", "آیا می‌خواهید از برنامه خارج شوید؟"))
        self.btnYes.setText(_translate("YesNoDialog", "بله"))
        self.btnNo.setText(_translate("YesNoDialog", "خیر"))
import UI.resource_rc
