# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YesNoDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YesNoDialog(object):
    def setupUi(self, YesNoDialog):
        YesNoDialog.setObjectName("YesNoDialog")
        YesNoDialog.resize(308, 136)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        YesNoDialog.setWindowIcon(icon)
        YesNoDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        YesNoDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        YesNoDialog.setModal(False)
        self.VLayoutMain = QtWidgets.QVBoxLayout(YesNoDialog)
        self.VLayoutMain.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.VLayoutMain.setContentsMargins(10, 10, 10, 10)
        self.VLayoutMain.setSpacing(10)
        self.VLayoutMain.setObjectName("VLayoutMain")
        self.HLayoutMessage = QtWidgets.QHBoxLayout()
        self.HLayoutMessage.setSpacing(10)
        self.HLayoutMessage.setObjectName("HLayoutMessage")
        self.lblIcon = QtWidgets.QLabel(YesNoDialog)
        self.lblIcon.setMinimumSize(QtCore.QSize(64, 64))
        self.lblIcon.setMaximumSize(QtCore.QSize(64, 64))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.lblIcon.setFont(font)
        self.lblIcon.setText("")
        self.lblIcon.setPixmap(QtGui.QPixmap(":/icons/resources/icons/question.png"))
        self.lblIcon.setScaledContents(True)
        self.lblIcon.setObjectName("lblIcon")
        self.HLayoutMessage.addWidget(self.lblIcon)
        self.lblMessage = QtWidgets.QLabel(YesNoDialog)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.lblMessage.setFont(font)
        self.lblMessage.setObjectName("lblMessage")
        self.HLayoutMessage.addWidget(self.lblMessage)
        self.VLayoutMain.addLayout(self.HLayoutMessage)
        self.HLayoutButtons = QtWidgets.QHBoxLayout()
        self.HLayoutButtons.setSpacing(10)
        self.HLayoutButtons.setObjectName("HLayoutButtons")
        self.btnYes = QtWidgets.QPushButton(YesNoDialog)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.btnYes.setFont(font)
        self.btnYes.setAutoDefault(False)
        self.btnYes.setDefault(True)
        self.btnYes.setObjectName("btnYes")
        self.HLayoutButtons.addWidget(self.btnYes)
        self.btnNo = QtWidgets.QPushButton(YesNoDialog)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.btnNo.setFont(font)
        self.btnNo.setAutoDefault(False)
        self.btnNo.setObjectName("btnNo")
        self.HLayoutButtons.addWidget(self.btnNo)
        self.VLayoutMain.addLayout(self.HLayoutButtons)

        self.retranslateUi(YesNoDialog)
        QtCore.QMetaObject.connectSlotsByName(YesNoDialog)

    def retranslateUi(self, YesNoDialog):
        _translate = QtCore.QCoreApplication.translate
        YesNoDialog.setWindowTitle(_translate("YesNoDialog", "خروج"))
        self.lblMessage.setText(_translate("YesNoDialog", "آیا می‌خواهید از برنامه خارج شوید؟"))
        self.btnYes.setText(_translate("YesNoDialog", "بله"))
        self.btnNo.setText(_translate("YesNoDialog", "خیر"))
import UI.resource_rc
